In [1]:
import pandas as pd
import numpy as np

In [2]:
my_list = [1,2,3]
arr = np.array(my_list)

In [3]:
arr

array([1, 2, 3])

In [4]:
my_mat = [[1,2,3], [4,5, 6],[7,8,9]]

In [5]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [7]:
np.zeros(4)

array([0., 0., 0., 0.])

In [8]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
np.ones(3)

array([1., 1., 1.])

In [10]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [13]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
np.random.rand(5)

array([0.57432392, 0.65215668, 0.69821011, 0.05466069, 0.06134272])

In [15]:
np.random.rand(5,5)

array([[0.85620631, 0.82712368, 0.60648716, 0.70464352, 0.25534278],
       [0.38226737, 0.34476668, 0.2426336 , 0.01336348, 0.29346017],
       [0.62443868, 0.66494817, 0.05448843, 0.76244204, 0.47009621],
       [0.07673351, 0.88052824, 0.29170624, 0.72589689, 0.07797054],
       [0.71471616, 0.96575697, 0.70211336, 0.91305931, 0.94185711]])

In [16]:
np.random.randn(2)

array([-0.62633133, -0.69905174])

In [17]:
np.random.randn(3,3)

array([[ 0.64419663, -1.05926768, -0.20923523],
       [ 0.54119036,  0.43396749, -0.23812055],
       [-0.49476378, -1.734816  ,  0.16607857]])

In [18]:
np.random.randint(1,100)

75

In [19]:
np.random.randint(0,100,10)

array([56, 39, 68, 87, 36, 85, 13, 85, 19, 74])

In [20]:
arr = np.arange(25)

In [21]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
ranarr = np.random.randint(0,50,10)

In [23]:
ranarr

array([16,  5, 15, 40, 28,  3,  5, 29,  5, 48])

In [24]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [25]:
np.max(ranarr)

48

In [26]:
ranarr.max()

48

In [27]:
np.min(ranarr)

3

In [28]:
ranarr

array([16,  5, 15, 40, 28,  3,  5, 29,  5, 48])

In [29]:
np.argmax(ranarr)

9

In [30]:
ranarr.argmax()

9

In [31]:
np.argmin(ranarr)

5

In [32]:
arr.shape

(25,)

In [33]:
arr1 = arr.reshape(5,5)

In [34]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
arr1.shape

(5, 5)

In [36]:
arr.dtype

dtype('int32')

In [37]:
from numpy.random import randint

In [38]:
randint(2,15)

12

## Numpy Indexing and Selection

In [39]:
arr = np.arange(0,11)

In [40]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr[4]

4

In [42]:
arr[2:6]

array([2, 3, 4, 5])

In [43]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [44]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [45]:
arr[0:5]= 100

In [46]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [47]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [48]:
arr_copy = arr.copy()

In [49]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [50]:
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [51]:
arr_copy[:] = 99

In [52]:
arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [53]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [54]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [55]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
arr_2d[1][1]

5

In [57]:
arr_2d[2][1]

8

In [58]:
arr_2d[2,2]

9

In [59]:
arr_2d[0:2,1:]

array([[2, 3],
       [5, 6]])

In [60]:
arr = np.arange(1,11)

In [61]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
bool_arr = arr > 5

In [63]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [64]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [65]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [66]:
arr[arr<4]

array([1, 2, 3])

In [67]:
arr_new = np.arange(0,50)
arr_new

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [68]:
arr_new = arr_new.reshape(5,10)

In [69]:
arr_new

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [70]:
arr_new.shape

(5, 10)

In [71]:
arr_new[1:3, 3:5]

array([[13, 14],
       [23, 24]])

## Numpy Operations

* Array with Array
* Array with Scalars
* Universal Array Functions

In [72]:
a1 = np.arange(11)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
a1 + a1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [74]:
a1 * a1

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [75]:
a1 -a1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [76]:
a1 *250

array([   0,  250,  500,  750, 1000, 1250, 1500, 1750, 2000, 2250, 2500])

In [77]:
a1/a1

<ipython-input-77-bb8096eb89ac>:1: RuntimeWarning: invalid value encountered in true_divide
  a1/a1


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [78]:
1/a1

<ipython-input-78-b886dbbb94de>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/a1


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [79]:
a1**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [80]:
np.sqrt(a1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [81]:
np.exp(a1)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [82]:
np.sin(a1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [83]:
np.log(a1)

<ipython-input-83-f50b4f369011>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])