In [1]:
import pandas as pd
import numpy as np

In [3]:
my_list = [1,2,3]
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_mat = [[1,2,3], [4,5, 6],[7,8,9]]

In [6]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,21,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
np.zeros(4)

array([0., 0., 0., 0.])

In [9]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
np.ones(3)

array([1., 1., 1.])

In [11]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [14]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [15]:
np.random.rand(5)

array([0.0289443 , 0.98271486, 0.29113113, 0.4012916 , 0.09225547])

In [16]:
np.random.rand(5,5)

array([[0.27625877, 0.94938961, 0.44021947, 0.33113895, 0.23312731],
       [0.95721905, 0.70621008, 0.69466571, 0.8175882 , 0.30992857],
       [0.19969327, 0.94855429, 0.48830653, 0.63597069, 0.44580126],
       [0.59442952, 0.63695894, 0.15465062, 0.45262363, 0.35479499],
       [0.64582307, 0.06386842, 0.03179286, 0.53635589, 0.51474208]])

In [17]:
np.random.randn(2)

array([ 1.00186413, -0.16826368])

In [19]:
np.random.randn(3,3)

array([[-1.78848376,  1.04336481,  0.6017216 ],
       [-0.71025401,  0.24380456, -0.54792478],
       [-0.71072564, -1.78655464,  0.75560102]])

In [21]:
np.random.randint(1,100)

96

In [22]:
np.random.randint(0,100,10)

array([48, 13, 99, 66, 68, 26, 27, 96, 34, 82])

In [23]:
arr = np.arange(25)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
ranarr = np.random.randint(0,50,10)

In [27]:
ranarr

array([20, 49,  8,  4, 20, 16, 25, 44, 32, 28])

In [28]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [29]:
np.max(ranarr)

49

In [30]:
ranarr.max()

49

In [31]:
np.min(ranarr)

4

In [33]:
ranarr

array([20, 49,  8,  4, 20, 16, 25, 44, 32, 28])

In [34]:
np.argmax(ranarr)

1

In [35]:
ranarr.argmax()

1

In [36]:
np.argmin(ranarr)

3

In [38]:
arr.shape

(25,)

In [41]:
arr1 = arr.reshape(5,5)

In [42]:
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
arr1.shape

(5, 5)

In [44]:
arr.dtype

dtype('int32')

In [46]:
from numpy.random import randint

In [47]:
randint(2,15)

13

## Numpy Indexing and Selection

In [48]:
arr = np.arange(0,11)

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr[4]

4

In [51]:
arr[2:6]

array([2, 3, 4, 5])

In [52]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [53]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [54]:
arr[0:5]= 100

In [55]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [56]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [57]:
arr_copy = arr.copy()

In [58]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [59]:
arr_copy

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [60]:
arr_copy[:] = 99

In [61]:
arr_copy

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [62]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [65]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [66]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
arr_2d[1][1]

5

In [68]:
arr_2d[2][1]

8

In [69]:
arr_2d[2,2]

9

In [74]:
arr_2d[0:2,1:]

array([[2, 3],
       [5, 6]])

In [76]:
arr = np.arange(1,11)

In [77]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
bool_arr = arr > 5

In [80]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [81]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [82]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [83]:
arr[arr<4]

array([1, 2, 3])

In [86]:
arr_new = np.arange(0,50)
arr_new

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [98]:
arr_new = arr_new.reshape(5,10)

In [100]:
arr_new

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [99]:
arr_new.shape

(5, 10)

In [103]:
arr_new[1:3, 3:5]

array([[13, 14],
       [23, 24]])